# Generated by Django 6.0.2 on 2026-02-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
